// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmqzxQW4-9AVhB25eL4hTIEk8q1LuaUU4',
    appId: '1:410448603553:web:ddea146658cb22060543e0',
    messagingSenderId: '410448603553',
    projectId: 'usersdata-12c4e',
    authDomain: 'usersdata-12c4e.firebaseapp.com',
    storageBucket: 'usersdata-12c4e.firebasestorage.app',
    measurementId: 'G-5ZENG1B1F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChS9t17NaF9GmtI92ao9d52GeuBZVsu2Y',
    appId: '1:410448603553:android:b6606332891e5cac0543e0',
    messagingSenderId: '410448603553',
    projectId: 'usersdata-12c4e',
    storageBucket: 'usersdata-12c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ-RvpXmDRW_h5HwqIiL6I_jy-bGnLZSw',
    appId: '1:410448603553:ios:b7910fe0f64196010543e0',
    messagingSenderId: '410448603553',
    projectId: 'usersdata-12c4e',
    storageBucket: 'usersdata-12c4e.firebasestorage.app',
    iosBundleId: 'com.example.userData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ-RvpXmDRW_h5HwqIiL6I_jy-bGnLZSw',
    appId: '1:410448603553:ios:b7910fe0f64196010543e0',
    messagingSenderId: '410448603553',
    projectId: 'usersdata-12c4e',
    storageBucket: 'usersdata-12c4e.firebasestorage.app',
    iosBundleId: 'com.example.userData',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmqzxQW4-9AVhB25eL4hTIEk8q1LuaUU4',
    appId: '1:410448603553:web:8a43979bc60cf1cf0543e0',
    messagingSenderId: '410448603553',
    projectId: 'usersdata-12c4e',
    authDomain: 'usersdata-12c4e.firebaseapp.com',
    storageBucket: 'usersdata-12c4e.firebasestorage.app',
    measurementId: 'G-PX34ZN964Y',
  );
}
